package com.training.portfolio;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * These tests define what "correct" means for MalformedAssetException and
 * AssetLineParser. Do not edit this file - implement the two classes until
 * every test here passes (`mvn test`).
 */
class AssetLineParserTest {

    private AssetLineParser parser;

    @BeforeEach
    void setUp() {
        parser = new AssetLineParser();
    }

    @Test
    void parsesAWellFormedLine() throws MalformedAssetException {
        Asset asset = parser.parseLine("A1001,EQUITY,15000.00");

        assertEquals("A1001", asset.getAssetId());
        assertEquals("EQUITY", asset.getAssetType());
        assertEquals(15000.00, asset.getValue(), 0.0001);
    }

    @Test
    void wrongNumberOfFieldsThrowsMalformedAssetException() {
        assertThrows(MalformedAssetException.class,
                () -> parser.parseLine("A1001,EQUITY"));
    }

    @Test
    void unknownAssetTypeThrowsMalformedAssetException() {
        assertThrows(MalformedAssetException.class,
                () -> parser.parseLine("A1001,CRYPTO,15000.00"));
    }

    @Test
    void nonNumericValueThrowsMalformedAssetExceptionWrappingNumberFormatException() {
        MalformedAssetException thrown = assertThrows(MalformedAssetException.class,
                () -> parser.parseLine("A1001,EQUITY,not-a-number"));

        assertInstanceOf(NumberFormatException.class, thrown.getCause());
    }

    @Test
    void negativeValueThrowsMalformedAssetException() {
        assertThrows(MalformedAssetException.class,
                () -> parser.parseLine("A1001,EQUITY,-500.00"));
    }

    @Test
    void parsePortfolioCollectsAllValidAssets() {
        List<String> lines = List.of(
                "A1001,EQUITY,15000.00",
                "A1002,BOND,5000.00",
                "A1003,CASH,250.50"
        );

        ParseSummary summary = parser.parsePortfolio(lines);

        assertEquals(3, summary.getValidAssets().size());
        assertTrue(summary.getErrors().isEmpty());
    }

    @Test
    void parsePortfolioSkipsBadLinesButKeepsGoing() {
        List<String> lines = List.of(
                "A1001,EQUITY,15000.00",
                "A1002,CRYPTO,5000.00",
                "A1003,BOND,not-a-number",
                "A1004,CASH,250.50"
        );

        ParseSummary summary = parser.parsePortfolio(lines);

        assertEquals(2, summary.getValidAssets().size());
        assertEquals(List.of("A1001", "A1004"),
                summary.getValidAssets().stream().map(Asset::getAssetId).toList());
        assertEquals(2, summary.getErrors().size());
    }
}
