package com.training.portfolio;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.NoSuchElementException;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

/**
 * These tests define what "correct" means for PortfolioReport.
 * Do not edit this file - implement PortfolioReport until every test here
 * passes (`mvn test`).
 */
class PortfolioReportTest {

    private PortfolioReport report;

    @BeforeEach
    void setUp() {
        report = new PortfolioReport();
    }

    @Test
    void newPortfolioHasNoAssets() {
        assertTrue(report.getAssets().isEmpty());
    }

    @Test
    void addAssetAddsToTheList() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));
        report.addAsset(new Asset("A1002", "BOND", 5000.0));

        assertEquals(2, report.getAssets().size());
    }

    @Test
    void getAssetsCannotBeUsedToMutateThePortfolio() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));

        assertThrows(UnsupportedOperationException.class,
                () -> report.getAssets().add(new Asset("A1002", "BOND", 1.0)));
    }

    @Test
    void totalValueOfEmptyPortfolioIsZero() {
        assertEquals(0.0, report.totalValue(), 0.0001);
    }

    @Test
    void totalValueSumsEveryAsset() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));
        report.addAsset(new Asset("A1002", "BOND", 5000.0));
        report.addAsset(new Asset("A1003", "CASH", 250.50));

        assertEquals(20250.50, report.totalValue(), 0.0001);
    }

    @Test
    void valueByAssetTypeGroupsAndSumsCorrectly() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));
        report.addAsset(new Asset("A1002", "EQUITY", 5000.0));
        report.addAsset(new Asset("A1003", "BOND", 2000.0));

        var byType = report.valueByAssetType();

        assertEquals(20000.0, byType.get("EQUITY"), 0.0001);
        assertEquals(2000.0, byType.get("BOND"), 0.0001);
        assertEquals(2, byType.size());
    }

    @Test
    void countByAssetTypeCountsAssetsPerType() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));
        report.addAsset(new Asset("A1002", "EQUITY", 5000.0));
        report.addAsset(new Asset("A1003", "BOND", 2000.0));

        var countByType = report.countByAssetType();

        assertEquals(2, countByType.get("EQUITY"));
        assertEquals(1, countByType.get("BOND"));
    }

    @Test
    void distinctAssetTypesReturnsEachTypeOnce() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));
        report.addAsset(new Asset("A1002", "EQUITY", 5000.0));
        report.addAsset(new Asset("A1003", "BOND", 2000.0));
        report.addAsset(new Asset("A1004", "CASH", 500.0));

        assertEquals(Set.of("EQUITY", "BOND", "CASH"), report.distinctAssetTypes());
    }

    @Test
    void highestValueAssetReturnsTheLargestHolding() {
        report.addAsset(new Asset("A1001", "EQUITY", 15000.0));
        report.addAsset(new Asset("A1002", "BOND", 42000.0));
        report.addAsset(new Asset("A1003", "CASH", 500.0));

        assertEquals("A1002", report.highestValueAsset().getAssetId());
    }

    @Test
    void highestValueAssetOnEmptyPortfolioThrows() {
        assertThrows(NoSuchElementException.class, () -> report.highestValueAsset());
    }
}
